### ISSUE TITLE
Not working with sbt 1.0

### ISSUE THREAD

**Issue by GMadorell** [tkawachi/sbt-repeat#2]
It results in dependency not found when using this plugin alongside sbt 1.0.x

Sample output:

```
sbt.librarymanagement.ResolveException: unresolved dependency: com.github.tkawachi#sbt-repeat;0.0.1: not found
```

It was working just fine with sbt 0.13.x

**Comment by tkawachi** [comment]
It's supported from 0.1.0. Please try it 😄
